//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Armer
{
    [Serializable]
    public class ServoStampedMsg : Message
    {
        public const string k_RosMessageName = "armer_msgs/ServoStamped";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public Geometry.PoseMsg pose;
        public float gain;
        public float threshold;

        public ServoStampedMsg()
        {
            this.header = new Std.HeaderMsg();
            this.pose = new Geometry.PoseMsg();
            this.gain = 0.0f;
            this.threshold = 0.0f;
        }

        public ServoStampedMsg(Std.HeaderMsg header, Geometry.PoseMsg pose, float gain, float threshold)
        {
            this.header = header;
            this.pose = pose;
            this.gain = gain;
            this.threshold = threshold;
        }

        public static ServoStampedMsg Deserialize(MessageDeserializer deserializer) => new ServoStampedMsg(deserializer);

        private ServoStampedMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            this.pose = Geometry.PoseMsg.Deserialize(deserializer);
            deserializer.Read(out this.gain);
            deserializer.Read(out this.threshold);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.pose);
            serializer.Write(this.gain);
            serializer.Write(this.threshold);
        }

        public override string ToString()
        {
            return "ServoStampedMsg: " +
            "\nheader: " + header.ToString() +
            "\npose: " + pose.ToString() +
            "\ngain: " + gain.ToString() +
            "\nthreshold: " + threshold.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
