//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Armer
{
    [Serializable]
    public class GuardedVelocityGoal : Message
    {
        public const string k_RosMessageName = "armer_msgs/GuardedVelocity";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.TwistStampedMsg twist_stamped;
        public GuardsMsg guards;

        public GuardedVelocityGoal()
        {
            this.twist_stamped = new Geometry.TwistStampedMsg();
            this.guards = new GuardsMsg();
        }

        public GuardedVelocityGoal(Geometry.TwistStampedMsg twist_stamped, GuardsMsg guards)
        {
            this.twist_stamped = twist_stamped;
            this.guards = guards;
        }

        public static GuardedVelocityGoal Deserialize(MessageDeserializer deserializer) => new GuardedVelocityGoal(deserializer);

        private GuardedVelocityGoal(MessageDeserializer deserializer)
        {
            this.twist_stamped = Geometry.TwistStampedMsg.Deserialize(deserializer);
            this.guards = GuardsMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.twist_stamped);
            serializer.Write(this.guards);
        }

        public override string ToString()
        {
            return "GuardedVelocityGoal: " +
            "\ntwist_stamped: " + twist_stamped.ToString() +
            "\nguards: " + guards.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Goal);
        }
    }
}
