//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Armer
{
    [Serializable]
    public class HomeGoal : Message
    {
        public const string k_RosMessageName = "armer_msgs/Home";
        public override string RosMessageName => k_RosMessageName;

        public float speed;
        //  m/s

        public HomeGoal()
        {
            this.speed = 0.0f;
        }

        public HomeGoal(float speed)
        {
            this.speed = speed;
        }

        public static HomeGoal Deserialize(MessageDeserializer deserializer) => new HomeGoal(deserializer);

        private HomeGoal(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.speed);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.speed);
        }

        public override string ToString()
        {
            return "HomeGoal: " +
            "\nspeed: " + speed.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Goal);
        }
    }
}
