//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Armer
{
    [Serializable]
    public class MoveToNamedPoseGoal : Message
    {
        public const string k_RosMessageName = "armer_msgs/MoveToNamedPose";
        public override string RosMessageName => k_RosMessageName;

        //  Goal definition
        public string pose_name;
        public float speed;
        //  m/s

        public MoveToNamedPoseGoal()
        {
            this.pose_name = "";
            this.speed = 0.0f;
        }

        public MoveToNamedPoseGoal(string pose_name, float speed)
        {
            this.pose_name = pose_name;
            this.speed = speed;
        }

        public static MoveToNamedPoseGoal Deserialize(MessageDeserializer deserializer) => new MoveToNamedPoseGoal(deserializer);

        private MoveToNamedPoseGoal(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.pose_name);
            deserializer.Read(out this.speed);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.pose_name);
            serializer.Write(this.speed);
        }

        public override string ToString()
        {
            return "MoveToNamedPoseGoal: " +
            "\npose_name: " + pose_name.ToString() +
            "\nspeed: " + speed.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Goal);
        }
    }
}
