//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Armer
{
    [Serializable]
    public class MoveToPoseGoal : Message
    {
        public const string k_RosMessageName = "armer_msgs/MoveToPose";
        public override string RosMessageName => k_RosMessageName;

        //  Goal definition
        public Geometry.PoseStampedMsg pose_stamped;
        public float speed;
        //  m/s

        public MoveToPoseGoal()
        {
            this.pose_stamped = new Geometry.PoseStampedMsg();
            this.speed = 0.0f;
        }

        public MoveToPoseGoal(Geometry.PoseStampedMsg pose_stamped, float speed)
        {
            this.pose_stamped = pose_stamped;
            this.speed = speed;
        }

        public static MoveToPoseGoal Deserialize(MessageDeserializer deserializer) => new MoveToPoseGoal(deserializer);

        private MoveToPoseGoal(MessageDeserializer deserializer)
        {
            this.pose_stamped = Geometry.PoseStampedMsg.Deserialize(deserializer);
            deserializer.Read(out this.speed);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.pose_stamped);
            serializer.Write(this.speed);
        }

        public override string ToString()
        {
            return "MoveToPoseGoal: " +
            "\npose_stamped: " + pose_stamped.ToString() +
            "\nspeed: " + speed.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Goal);
        }
    }
}
